server:
  port: 8092

spring:
  application:
    name: fraud
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: rootpassword
      database: fraud
      port: 27018
      host: localhost
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest
    exchange:
      name: fraud-to-notification
    queue:
      name: fraudsters-%s

eureka:
  client:
    service-url:
      defaultZone: docker
    register-with-eureka: true
    fetch-registry: true
